# Generated by Django 4.2.4 on 2023-09-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=4)),
                ('gear', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default=' $ /day', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('postalcode', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='Finland', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='', max_length=20)),
                ('adress', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='@gmail.com', max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
