# Generated by Django 4.2.4 on 2023-08-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='laku', max_length=20)),
                ('model', models.CharField(default=3, max_length=20)),
                ('year', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('gear', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('postalcode', models.IntegerField(default=5)),
                ('country', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='laku', max_length=20)),
                ('adress', models.CharField(default=3, max_length=20)),
                ('phone', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('mail', models.IntegerField(default=3)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
