# Generated by Django 4.2.4 on 2023-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_car_brand_remove_customer_car_car_carname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(default=' $ per day', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(default='@gmail.com', max_length=50),
        ),
    ]
